### ISSUE TITLE
TypeError: cannot pickle 'weakref' object

### ISSUE THREAD

**Issue by HaleAkrami** [hasan1292/mDDPM#2]
Hello,

I am trying to run your code but I get this error:
TypeError: cannot pickle 'weakref' object

Can you please help me with it?

Thanks

**Comment by hasan1292** [comment]
Hi. Can you be more elaborate? In which python file you're getting the error? Which line of code?

Can you copy/paste your error from cmd prompt/ide?

**Comment by Bhavay192** [comment]
Hi @hasan1292 , I'm also getting this error while training model on multiple GPUs. This error comes with multi-processing I believe. I'm not able to find a fix around this.
Thanks

**Comment by Li-cafe** [comment]
hi，I encountered the same problem when training with multiple GPUs. When I use only one GPU with more than 12G of single memory for training, the error disappears.

> Hi @hasan1292 , I'm also getting this error while training model on multiple GPUs. This error comes with multi-processing I believe. I'm not able to find a fix around this. Thanks

**Comment by Bhavay-2001** [comment]
Hi @Li-cafe, I resolved the issue with multiple GPUs as well. You need to comment out that code which uses 'weakref' problem. It won't affect the training as it just used for some logging purposes. Thanks

**Comment by hwli-dev** [comment]
> Hi @Li-cafe, I resolved the issue with multiple GPUs as well. You need to comment out that code which uses 'weakref' problem. It won't affect the training as it just used for some logging purposes. Thanks

@Bhavay-2001 Which part should be commented out? There is no code related to the commented-out part in my error stack trace.
Error executing job with overrides: ['experiment=MIDL23_DDPM/DDPM']
Traceback (most recent call last):
  File "/data/hongweili/code/myddpm/run.py", line 38, in main
    return train(config)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/hydra/main.py", line 44, in decorated_main
    return task_function(cfg_passthrough)
  File "/data/hongweili/code/myddpm/src/train.py", line 134, in train
    trainer.fit(model, datamodule_train)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit
    self._call_and_handle_interrupt(
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
    self._dispatch()
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 173, in start_training
    self.spawn(self.new_process, trainer, self.mp_queue, return_result=False)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 201, in spawn
    mp.spawn(self._wrapped_function, args=(function, args, kwargs, return_queue), nprocs=self.num_processes)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref' object

**Comment by sun5030** [comment]
Hello, I encountered the same issue as you did. Have you resolved it? Did you comment out any part of the code, or did you find another solution? @hwli-dev thanks

**Comment by sun5030** [comment]
Hello, I encountered the same issue as you did. Have you resolved it? Did you comment out any part of the code, or did you find another solution? @hasan1292

**Comment by sun5030** [comment]
> > Hi @Li-cafe, I resolved the issue with multiple GPUs as well. You need to comment out that code which uses 'weakref' problem. It won't affect the training as it just used for some logging purposes. Thanks
> 
> @Bhavay-2001 Which part should be commented out? There is no code related to the commented-out part in my error stack trace. Error executing job with overrides: ['experiment=MIDL23_DDPM/DDPM'] Traceback (most recent call last): File "/data/hongweili/code/myddpm/run.py", line 38, in main return train(config) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/hydra/main.py", line 44, in decorated_main return task_function(cfg_passthrough) File "/data/hongweili/code/myddpm/src/train.py", line 134, in train trainer.fit(model, datamodule_train) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit self._call_and_handle_interrupt( File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt return trainer_fn(*args, **kwargs) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl self._run(model, ckpt_path=ckpt_path) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run self._dispatch() File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch self.training_type_plugin.start_training(self) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 173, in start_training self.spawn(self.new_process, trainer, self.mp_queue, return_result=False) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 201, in spawn mp.spawn(self._wrapped_function, args=(function, args, kwargs, return_queue), nprocs=self.num_processes) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn return start_processes(fn, args, nprocs, join, daemon, start_method='spawn') File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes process.start() File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/process.py", line 121, in start self._popen = self._Popen(self) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/context.py", line 284, in _Popen return Popen(process_obj) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in **init** super().**init**(process_obj) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/popen_fork.py", line 19, in **init** self._launch(process_obj) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch reduction.dump(process_obj, fp) File "/data/hongweili/anaconda3/envs/pddpm-uad/lib/python3.9/multiprocessing/reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj) TypeError: cannot pickle 'weakref' object

Hello, I encountered the same issue as you did. Have you resolved it? Did you comment out any part of the code, or did you find another solution? @hwli-dev thanks

**Comment by sun5030** [comment]
> Hi @Li-cafe, I resolved the issue with multiple GPUs as well. You need to comment out that code which uses 'weakref' problem. It won't affect the training as it just used for some logging purposes. Thanks

Hello, I encountered the same issue as you did. Have you resolved it? Did you comment out any part of the code, or did you find another solution? thanks
